baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Taking time to look'
theme = "paperesque"
cleanDestinationDir = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[author]
  name = "takingtimetolook"
  homepage = "https://takingtimetolook.github.io/"


[markup]
  # This is the default from Hugo 0.60.0 onwards, but we're setting config
  # for it below, so make it explicit
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    # Optional for your site. Enabled so that we can use {.list-unstyled} in _index.md
    [markup.goldmark.parser.attribute]
        block = true

# Required to render HTML tags in the hugoExampleSite examples.
[markup.goldmark.renderer]
  unsafe = true

# I can't remember if this is required for syntax highlighting or not.
pygmentsUseClasses = true

# Uncomment these lines for droplist / resource removal support! See the
# README for more details

# [outputs]
# page = ["HTML", "droplist"]

[params]
# Turn this on if you want to disable margin notes everywhere!
# disableMarginNotes = true

# Ensure that there are *no* [[params.menu]] sections here so that the _index.md
# file will be respected
# [[params.menu]]
#   name = "my favourite bird"
#   url = "posts/kookaburra/"

# Customize your top-right menu links here.

[[params.topmenu]]
  name = "About"
  url = "about"

