baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Taking time to look'
theme = "journal"
cleanDestinationDir = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[author]
  name = "takingtimetolook"
  homepage = "https://takingtimetolook.github.io/"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
