baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Taking time to see'
theme = "diary"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[author]
  name = "takingtimetolook"
  homepage = "https://takingtimetolook.github.io/"
